sudo: required
services:
  - docker

before_install:
  - docker build -t vonghard/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vonghard/react-test npm test -- --coverage

after_success:
  - docker build -t vonghard/multi_client ./client
  - docker build -t vonghard/multi_nginx ./nginx
  - docker build -t vonghard/multi_server ./server
  - docker build -t vonghard/multi_worker ./worker

# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push images to HUB
  - docker push vonghard/multi_client
  - docker push vonghard/multi_nginx
  - docker push vonghard/multi_server
  - docker push vonghard/multi_worker

deploy:
  provide: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-192540139408
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
