sudo: required
services:
  - docker

before_install:
  - docker build -t vong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vong/react-test npm test -- --coverage

after_success:
  - docker build -t vong/multi_client ./client
  - docker build -t vong/multi_nginx ./nginx
  - docker build -t vong/multi_server ./server
  - docker build -t vong/multi_worker ./worker

# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push images to HUB
  - docker push vonghard/multi_client
  - docker push vonghard/multi_nginx
  - docker push vonghard/multi_server
  - docker push vonghard/multi_worker
